version: '3.8'

services:
  fastapi:
    build:
      context: .  # Use the current directory
      dockerfile: Dockerfile
    image: gcr.io/bigdatateam5/fastapi-app  # Set the correct image name
    container_name: fastapi_service
    ports:
      - "8080:8080"
    env_file: 
      - .env  # Load environment variables
    volumes:
      - .:/app  # Mount the local directory
